modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/KURONAMI333/forbidden-arcanus-emc/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="forbidden_arcanus_emc.png"
displayURL="https://github.com/KURONAMI333/forbidden-arcanus-emc"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="projecte"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forbidden_arcanus"
    type="required"
    versionRange="[2.6.0,)"
    ordering="AFTER"
    side="BOTH"
